version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: docker/jenkins/Dockerfile
    container_name: jenkins_fairplay
    privileged: true
    user: root # Allows Jenkins to run Docker commands
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - fairplay_network

networks:
  fairplay_network:
    driver: bridge

volumes:
  jenkins_data:
