version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: fairplay_db
    restart: always
    environment:
      POSTGRES_USER: fairplay_user
      POSTGRES_PASSWORD: fairplay_pass
      POSTGRES_DB: fairplay_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  backend:
    build: .
    container_name: fairplay_backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5001
      - CLIENT_URL=${CLIENT_URL}
      - TEACHER_SECRET=${TEACHER_SECRET}
    depends_on:
      - db
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: fairplay_prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: fairplay_grafana
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
